version: '2.0.0'
debugMode: false
localChatRadius: 25
whisperChatRadius: 2
yellChatRadius: 50
emoteRadius: 25
changeNameCooldown: 300
localChatColor: "blue"
yellChatColor: "red"
emoteColor: "gray"
rightClickToViewCard: true
localOOCChatRadius: 25
localOOCChatColor: "gray"
positiveAlertColor: "green"
neutralAlertColor: "aqua"
negativeAlertColor: "red"
chatFeaturesEnabled: true
overrideGlobal: false
preventSelfBirding: false
birdSpeed: 20