name: MedievalRoleplayEngine
version: "1.6.1-beta-1"
author: DanTheTechMan
main: dansplugins.rpsystem.MedievalRoleplayEngine
api-version: "1.13"
softdepend: [MedievalFactions]

commands:
  card:
  bird:
  local:
  rp:
  global:
  ooc:
  emote:
  me:
  roll:
  dice:
  title:
  yell:
  whisper:
  rphelp:
  rpconfig:
  lo:

permissions:
  rp.bird:
    default: true
  rp.card.show:
    default: true
  rp.card.show.others:
    default: true
  rp.card.help:
    default: true
  rp.card.name:
    default: true
  rp.card.race:
    default: true
  rp.card.subculture:
    default: true
  rp.card.religion:
    default: true
  rp.card.age:
    default: true
  rp.card.gender:
    default: true
  rp.local:
    default: true
  rp.rp:
    default: true
  rp.global:
    default: true
  rp.ooc:
    default: true
  rp.emote:
    default: true
  rp.me:
    default: true
  rp.roll:
    default: true
  rp.dice:
    default: true
  rp.title:
    default: true
  rp.yell:
    default: true
  rp.whisper:
    default: true
  rp.help:
    default: true
  rp.localOOC:
    default: true
  rp.card.forcesave:
    default: op
  rp.card.forceload:
    default: op
  rp.config:
    default: op