name: MedievalRoleplayEngine
version: '${project.version}'
author: Daniel Stephenson
main: dansplugins.rpsystem.MedievalRoleplayEngine
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  medievalroleplayengine:
  mre:
  roleplay:
  rp:

permissions:
  mre.bird:
    default: true
  mre.card:
    default: true
  mre.local:
    default: true
  mre.global:
    default: true
  mre.emote:
    default: true
  mre.roll:
    default: true
  mre.title:
    default: true
  mre.yell:
    default: true
  mre.whisper:
    default: true
  mre.help:
    default: true
  mre.localOOC:
    default: true
  mre.set:
    default: true
  mre.set.others:
    default: op
  mre.character:
    default: true
  mre.stats:
    default: true
  mre.unset:
    default: true
  mre.unset.others:
    default: op
  mre.config:
    default: op