name: MedievalRoleplayEngine
version: 2.0-alpha-5
author: Daniel Stephenson
main: dansplugins.rpsystem.MedievalRoleplayEngine
api-version: 1.13
softdepend: [PlaceholderAPI, MedievalFactions, Mailboxes]

commands:
  medievalroleplayengine:
  mre:
  roleplay:
  rp:

permissions:
  rp.bird:
    default: true
  rp.card:
    default: true
  rp.local:
    default: true
  rp.global:
    default: true
  rp.emote:
    default: true
  rp.roll:
    default: true
  rp.title:
    default: true
  rp.yell:
    default: true
  rp.whisper:
    default: true
  rp.help:
    default: true
  rp.localOOC:
    default: true
  rp.set:
    default: true
  rp.character:
    default: true
  rp.stats:
    default: true
  rp.unset:
    default: true
  rp.config:
    default: op
  rp.force:
    default: op