name: MedievalRoleplayEngine
version: "1.5.0.1"
author: DanTheTechMan
main: rpsystem.MedievalRoleplayEngine
api-version: "1.13"

commands:
  card:
  bird:
  local:
  rp:
  global:
  ooc:
  emote:
  me:
  roll:
  dice:
  title:
  yell:
  whisper:
  rphelp: