# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.217.4/containers/java-8/.devcontainer/base.Dockerfile

# [Choice] Debian OS version (use bullseye on local arm64/Apple Silicon): buster, bullseye
ARG VARIANT="bullseye"
FROM maven:3.8-eclipse-temurin-21-alpine

WORKDIR /workspaces/Medieval-Roleplay-Engine
